// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTickets.Entities.Entities;

public partial class Agosto2022V3
{
    public string Empresa { get; set; }

    public string Razon { get; set; }

    public string Telefono { get; set; }

    public string Rtn { get; set; }

    public string Diremp { get; set; }

    public string Identidad { get; set; }

    public string Nombre { get; set; }

    public string Tel { get; set; }

    public string Cel { get; set; }
}