// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTickets.Entities.Entities;

public partial class Base20Meno
{
    public string NombrePropietario { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public string DireccionCliente { get; set; }

    public string CodigoCarnet { get; set; }

    public string CorreoCliente { get; set; }

    public string TelefonosCliente { get; set; }
}