// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTickets.Entities.Entities;

public partial class Base3
{
    public string Identidad { get; set; }

    public string PrimerNombre { get; set; }

    public string SegundoNombre { get; set; }

    public string PrimerApellido { get; set; }

    public string SegundoApellido { get; set; }

    public double? Telefono { get; set; }

    public double? Monto { get; set; }

    public string Direccion1 { get; set; }

    public string Direccion2 { get; set; }

    public double? Usuario { get; set; }

    public double? Estado { get; set; }
}