// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTickets.Entities.Entities;

public partial class BaseClientesEquifax
{
    public string FcIdentidad { get; set; }

    public int? FiScoreActual { get; set; }

    public int? FiScore1 { get; set; }

    public int? FiScore2 { get; set; }

    public int? FiScore3 { get; set; }

    public int? FiScore4 { get; set; }

    public int? FiScore5 { get; set; }

    public string FcTelefonos { get; set; }
}