// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTickets.Entities.Entities;

public partial class Base20MenosDepuradum
{
    public string FcIdentidad { get; set; }

    public string FcNombreCliente { get; set; }

    public string FcDireccion { get; set; }

    public string FcCorreoElectronico { get; set; }

    public string FcTelefonos { get; set; }
}