// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTickets.Entities.Entities;

public partial class CallCenterGestionBitacora
{
    public string FcIdentidad { get; set; }

    public string FcUsuario { get; set; }

    public int? FiEstado { get; set; }

    public string FcComentarioAdicional { get; set; }

    public DateTime? FdFechaGestion { get; set; }
}