// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTickets.Entities.Entities;

public partial class CallCenterAgendum
{
    public string FcIdentidad { get; set; }

    public string FcUsuario { get; set; }

    public string FcDetalle { get; set; }

    public DateTime FdFechaGestion { get; set; }

    public DateTime FdFechaAgenda { get; set; }

    public int FiActivo { get; set; }
}