// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTickets.Entities.Entities;

public partial class CallCenterUsuario
{
    public string FcUsuario { get; set; }

    public string FcNombreUsuario { get; set; }

    public string FcNombreCorto { get; set; }

    public string FcPassword { get; set; }

    public byte FiEstado { get; set; }

    public DateTime FdUltimoLogueo { get; set; }
}