// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTickets.Entities.Entities;

public partial class CallCenterPropuestaEconomica
{
    public short FcIdproducto { get; set; }

    public decimal FnObligacionesRangoInferior { get; set; }

    public decimal FnObligacionesRangoSuperior { get; set; }

    public decimal FnIngresosRangoInferior { get; set; }

    public decimal FnIngresosRangoSuperior { get; set; }

    public decimal FnOferta { get; set; }
}