// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTickets.Entities.Entities;

public partial class CallCenterEstado
{
    public int? FiEstado { get; set; }

    public string FcDetalleEstado { get; set; }

    public int? FiEnProcesoLdc { get; set; }

    public int? FiProcesoAdicional { get; set; }

    public int? FiTipoMovimiento { get; set; }

    public int? FiContactable { get; set; }
}