// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTickets.Entities.Entities;

public partial class Carga3
{
    public string Identidad { get; set; }

    public double? Sucural { get; set; }

    public string Nombre { get; set; }

    public string ApellidoP { get; set; }

    public string ApellidoM { get; set; }

    public string DirecionDomicilio { get; set; }

    public double? Telefono { get; set; }

    public double? Propuesto { get; set; }
}