// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTickets.Entities.Entities;

public partial class CargaCallCenter
{
    public string Identidad { get; set; }

    public string PrimerNombre { get; set; }

    public string SegundoNombre { get; set; }

    public string PrimerApp { get; set; }

    public string SegundoApp { get; set; }

    public double? PropuestaTope48 { get; set; }

    public string Telefono { get; set; }

    public string Direccion { get; set; }

    public string Colonia { get; set; }

    public string Ciudad { get; set; }

    public string FcUsuario { get; set; }

    public string FiEstado { get; set; }

    public string FecUltGest { get; set; }
}