// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTickets.Entities.Entities;

public partial class CargaCc5
{
    public string Identidad { get; set; }

    public string Pnombre { get; set; }

    public string Snombre { get; set; }

    public string Pappellido { get; set; }

    public string Sapellido { get; set; }

    public double? Oferta { get; set; }

    public double? Telefono { get; set; }

    public string Dir1 { get; set; }

    public string Dir2 { get; set; }

    public double? Usuario { get; set; }

    public string UltimaGestion { get; set; }

    public double? BaseAnterior { get; set; }

    public double? Bloqueo { get; set; }

    public double? Score { get; set; }
}