// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTickets.Entities.Entities;

public partial class CatalogoManuale
{
    public int FiIdmanual { get; set; }

    public DateTime FdFechaCreacion { get; set; }

    public int FiIdusuarioAutor { get; set; }

    public string FcTitulo { get; set; }

    public string FcDescripcion { get; set; }

    public DateTime? FdFechaUltimaModificacion { get; set; }

    public int? FiIdusuarioUltimaModificacion { get; set; }

    public byte FiIdestado { get; set; }

    public int FiIdtipoManual { get; set; }
}