// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTickets.Entities.Entities;

public partial class CatalogoManualDetalle
{
    public int FiIdmanualDetalle { get; set; }

    public int FiIdsolicitudManual { get; set; }

    public int FiIdusuarioCreador { get; set; }

    public int FiNumeroPagina { get; set; }

    public DateTime FdFechaRegistro { get; set; }

    public string FcTipoArchivo { get; set; }

    public string FcNombreArchivo { get; set; }

    public string FcRutaArchivo { get; set; }

    public string FcUrl { get; set; }
}