// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTickets.Entities.Entities;

public partial class Cne
{
    public string FcIdentidad { get; set; }

    public string FcPrimerNombre { get; set; }

    public string FcSegundoNombre { get; set; }

    public string FcPrimerApellido { get; set; }

    public string FcSegundoApellido { get; set; }

    public DateOnly? FdFechadeNacimiento { get; set; }

    public byte? FiSexo { get; set; }
}