// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTickets.Entities.Entities;

public partial class Contador
{
    public int FiIdconsecutivo { get; set; }

    public string FcDescripcion { get; set; }

    public int FiTipoTransaccion { get; set; }

    public int FiNoConsecutivo { get; set; }

    public short FiIdapp { get; set; }
}