// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTickets.Entities.Entities;

public partial class Dat012024
{
    public string InformacionLaboral { get; set; }

    public string Empresa { get; set; }

    public string Razon { get; set; }

    public string Rtn { get; set; }

    public string Diremp { get; set; }

    public string Telemp { get; set; }

    public string Ciudad { get; set; }

    public string Ident { get; set; }

    public string Nombre { get; set; }

    public string Tel { get; set; }

    public string Movil { get; set; }

    public string Direc2 { get; set; }
}