// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTickets.Entities.Entities;

public partial class Demanda
{
    public string NoPrestamo { get; set; }

    public string Nombre { get; set; }

    public string Vehiculo { get; set; }

    public string Identidad { get; set; }

    public decimal? TotalVencido { get; set; }

    public decimal? TotalAdeudado { get; set; }

    public string Trabajo { get; set; }

    public string SolicitudAbogado { get; set; }
}