// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTickets.Entities.Entities;

public partial class Hoja1X2
{
    public string FcIdentidad { get; set; }

    public string FcPrimerNombre { get; set; }

    public string FcSegundoNombre { get; set; }

    public string FcPrimerApellido { get; set; }

    public string FcSegundoApellido { get; set; }

    public double? FiMonto { get; set; }

    public string FcTelefono { get; set; }

    public string FcDireccion1 { get; set; }

    public string FcDireccion2 { get; set; }

    public double? FcUsuario { get; set; }

    public double? Fiestado { get; set; }

    public string FechaUltimaGestion { get; set; }
}