// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTickets.Entities.Entities;

public partial class HojaX
{
    public string Ntienda { get; set; }

    public string Ciudad { get; set; }

    public string Nombre { get; set; }

    public string PrimerApp { get; set; }

    public string SegundoApp { get; set; }

    public string Direccion { get; set; }

    public string Colonia { get; set; }

    public double? Telefono { get; set; }

    public string IdentidadUnica { get; set; }

    public string Id { get; set; }

    public double? Longitud { get; set; }

    public DateTime? FechaAlta { get; set; }

    public double? Antigedad { get; set; }

    public double? IngresoMensualAprobado { get; set; }

    public double? IngresoEstimadoMensual { get; set; }

    public string TipoDeCliente { get; set; }

    public double? CapacidaddePagoMensual { get; set; }

    public double? Propuesta48 { get; set; }

    public double? Propuesta36 { get; set; }

    public double? Propuesta24 { get; set; }

    public double? PropuestaTope48 { get; set; }

    public double? CapacidadDePagoSemanal { get; set; }

    public double? CapacidadDisponible { get; set; }

    public double? MontoUtilizado { get; set; }

    public DateTime? FechaUltimaActividad { get; set; }
}