// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTickets.Entities.Entities;

public partial class HojaX1
{
    public string Ntienda { get; set; }

    public string Ciudad { get; set; }

    public string Nombre { get; set; }

    public string PrimerApp { get; set; }

    public string SegundoApp { get; set; }

    public string Direccion { get; set; }

    public string Colonia { get; set; }

    public string Telefono { get; set; }

    public double? Identidad { get; set; }

    public string Id { get; set; }

    public double? Repetido { get; set; }

    public double? Longitud { get; set; }

    public DateTime? FechaAlta { get; set; }

    public double? IngresoMensualAprobado { get; set; }

    public double? CapacidadDePagoSemanal { get; set; }

    public double? CapacidadDisponible { get; set; }

    public double? MontoUtilizado { get; set; }

    public DateTime? FechaUltimaActividad { get; set; }
}