// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTickets.Entities.Entities;

public partial class Hojax3
{
    public string FcIdentidad { get; set; }

    public string FcPrimerNombre { get; set; }

    public string FcSegundoNombre { get; set; }

    public string FcPrimerApellido { get; set; }

    public string FcSegundoApellido { get; set; }

    public double? FnOferta { get; set; }

    public string FcTelefono { get; set; }

    public string FcDireccion1 { get; set; }

    public string FcDireccion2 { get; set; }

    public double? FcUsuario { get; set; }

    public double? FiEstado { get; set; }

    public string FdFechaUltimaGestion { get; set; }

    public double? FiBaseAnterior { get; set; }

    public double? FiBloqueo { get; set; }

    public double? FiUltimoScore { get; set; }
}