// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTickets.Entities.Entities;

public partial class HojaIhss2023Feb
{
    public string Empresa { get; set; }

    public string Razon { get; set; }

    public string Rtn { get; set; }

    public string Direccion { get; set; }

    public string Telefono { get; set; }

    public string Ciudad { get; set; }

    public string Identidad { get; set; }

    public string Nombre { get; set; }

    public string TelEmple { get; set; }

    public string Celular { get; set; }

    public string Direc { get; set; }

    public string Base { get; set; }
}