// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTickets.Entities.Entities;

public partial class Ihssbasemayo2022
{
    public string Trabajo { get; set; }

    public string Rtn { get; set; }

    public string Ciudad { get; set; }

    public string Identidad { get; set; }

    public string Nombre { get; set; }

    public string Direc { get; set; }
}