// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTickets.Entities.Entities;

public partial class Ihss022023
{
    public string Empresa { get; set; }

    public string Razon { get; set; }

    public string Rtn { get; set; }

    public string Direccion { get; set; }

    public string Telefono { get; set; }

    public string Identidad { get; set; }

    public string Nombre { get; set; }
}