// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTickets.Entities.Entities;

public partial class Ihss2019
{
    public string FcIdentidad { get; set; }

    public string FcNombre { get; set; }

    public string FcEmpresa { get; set; }

    public string Fcrtn { get; set; }

    public string FcDireccionEmpresa { get; set; }
}