// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTickets.Entities.Entities;

public partial class InformacionPlacasIp
{
    public int FiIdinformacionPlaca { get; set; }

    public string FcPlaca { get; set; }

    public string FcMarca { get; set; }

    public string FcColor { get; set; }

    public int FilDperiodo { get; set; }

    public decimal FnTasaVehicularDebito { get; set; }

    public decimal FnTasaVehicularCredito { get; set; }

    public decimal FnTasaVehicularSaldo { get; set; }

    public decimal FnMultaVehicularDebito { get; set; }

    public decimal FnMultaVehicularCredito { get; set; }

    public decimal FnMultaVehicularSaldo { get; set; }

    public decimal FnSaldosAnterioresVehicularDebito { get; set; }

    public decimal FnSaldosAnterioresVehicularCredito { get; set; }

    public decimal FnSaldosAnterioresVehicularSaldo { get; set; }

    public decimal FnTasaMunicipalDebito { get; set; }

    public decimal FnTasaMunicipalCredito { get; set; }

    public decimal FnTasaMunicipalSaldo { get; set; }

    public decimal FnMultaMunicipalDebito { get; set; }

    public decimal FnMultaMunicipalCredito { get; set; }

    public decimal FnMultaMunicipalSaldo { get; set; }

    public decimal FnSaldosAnterioresMunicipalesDebito { get; set; }

    public decimal FnSaldosAnterioresMunicipalesCredito { get; set; }

    public decimal FnSaldosAnterioresMunicipalesSaldo { get; set; }

    public decimal FnContribucionSigloXxidebito { get; set; }

    public decimal FnContribucionSigloXxicredito { get; set; }

    public decimal FnContribucionSigloXxisaldo { get; set; }

    public decimal FnSaldosAnterioresSigloXxidebito { get; set; }

    public decimal FnSaldosAnterioresSiglosXxicredito { get; set; }

    public decimal FnSaldosAnterioresSiglosXxisaldo { get; set; }

    public decimal FnValorPlacaDebito { get; set; }

    public decimal FnValorPlacaCredito { get; set; }

    public decimal FnValorPlacaSaldo { get; set; }

    public decimal FilDtotalMatricula { get; set; }

    public int FiCambiodePropietarioCantidad { get; set; }

    public decimal FnCambiodePropietarioMonto { get; set; }

    public int FiCambioPlacaCantidad { get; set; }

    public decimal FnCambioPlacaMonto { get; set; }

    public int FiTotalCantidad { get; set; }

    public decimal FnTotalMonto { get; set; }

    public decimal FnTotalaPagar { get; set; }

    public DateTime FdFechaConsulta { get; set; }
}