// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTickets.Entities.Entities;

public partial class Planilla2010
{
    public string Ide { get; set; }

    public string Numeafil { get; set; }

    public string Nombre { get; set; }

    public decimal Sexo { get; set; }

    public string Fechnaci { get; set; }

    public string Deparesi { get; set; }

    public string Muniresi { get; set; }

    public string Aldearesi { get; set; }

    public string Caseresi { get; set; }

    public string Colonia { get; set; }

    public string Diremp { get; set; }

    public string Telemp { get; set; }

    public string Numpa { get; set; }

    public string Nombrepat { get; set; }

    public string Telefono { get; set; }

    public string Ciudad { get; set; }

    public string Salario { get; set; }

    public string Fechnaci1 { get; set; }

    public decimal Depto { get; set; }

    public decimal Muni { get; set; }

    public string Raozosoci { get; set; }

    public string Direvieja { get; set; }

    public decimal Filtro { get; set; }

    public string Mestrab { get; set; }

    public string Email { get; set; }
}