// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTickets.Entities.Entities;

public partial class Prestadito
{
    public double? Lista { get; set; }

    public string Identidad { get; set; }

    public double? SaldoAzteca { get; set; }

    public double? ScoreActual { get; set; }

    public double? Score1 { get; set; }

    public double? Score2 { get; set; }

    public double? Score3 { get; set; }

    public double? Score4 { get; set; }

    public double? Score5 { get; set; }

    public string Telefonos { get; set; }

    public string F11 { get; set; }
}