// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTickets.Entities.Entities;

public partial class ProcesoArchivosSaf
{
    public string FcNombreArchivo { get; set; }

    public string FcUbicacionArchivo { get; set; }
}