// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTickets.Entities.Entities;

public partial class RequerimientosContadore
{
    public int FiIdcontador { get; set; }

    public string FcDescripcionContador { get; set; }

    public int FiIdnumeroSiguiente { get; set; }

    public string FcToken { get; set; }
}