// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTickets.Entities.Entities;

public partial class RequerimientosArea
{
    public short FiIdarea { get; set; }

    public string FcDescripcion { get; set; }

    public string FcCorreoElectronico { get; set; }

    public int FiIdusuarioResponsable { get; set; }
}