// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTickets.Entities.Entities;

public partial class RequerimientosEstado
{
    public byte FiIdestado { get; set; }

    public string FcDescripcionEstado { get; set; }

    public string FcClaseColor { get; set; }
}