// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTickets.Entities.Entities;

public partial class Requerimiento
{
    public int FiIdrequerimiento { get; set; }

    public DateTime FdAltaRequerimiento { get; set; }

    public short FiIdapp { get; set; }

    public int FiIdusuario { get; set; }

    public string FcTituloRequerimiento { get; set; }

    public byte FiIdareaAsignada { get; set; }

    public byte FiIdestado { get; set; }

    public string FcDetalleRequerimiento { get; set; }

    public string FcResolucion { get; set; }

    public DateTime? FdUltimaActualizacion { get; set; }

    public DateTime? FdCierreRequerimiento { get; set; }
}