// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTickets.Entities.Entities;

public partial class RequerimientosBitacorasEstado
{
    public int FiIdrequerimiento { get; set; }

    public int FIdiusuario { get; set; }

    public DateTime FdFechaInicioEstado { get; set; }

    public DateTime? FdFechaFinEstado { get; set; }

    public int FiIdestado { get; set; }

    public int FiIdapp { get; set; }

    public string FcToken { get; set; }
}