// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTickets.Entities.Entities;

public partial class RequerimientosBitacora1
{
    public int FiIdrequerimiento { get; set; }

    public DateTime FdBitacora { get; set; }

    public short FiIdapp { get; set; }

    public int FiIdusuario { get; set; }

    public byte FiEstadoAnterior { get; set; }

    public byte FiEstadoActual { get; set; }

    public string FcResolucion { get; set; }
}