// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTickets.Entities.Entities;

public partial class RequerimientosMaestro
{
    public int FiIdrequerimiento { get; set; }

    public DateTime FdFechaCreacion { get; set; }

    public int FiIdusuarioSolicitante { get; set; }

    public string FiIdipusuarioSolicitante { get; set; }

    public string FcTituloRequerimiento { get; set; }

    public string FcDescripcionRequerimiento { get; set; }

    public byte FiIdestadoRequerimiento { get; set; }

    public DateTime FdFechaAsignacion { get; set; }

    public int FiIdusuarioAsignado { get; set; }

    public DateTime FdFechadeCierre { get; set; }

    public int FiTiempodeDesarrollo { get; set; }

    public byte FiCategoriadeDesarrollo { get; set; }

    public byte FiTipoRequerimiento { get; set; }

    public byte FiIdareaSolicitante { get; set; }

    public decimal FnValoracionRequerimiento { get; set; }

    public DateTime? FdFechaUltimaModificacion { get; set; }

    public int? FiIdusuarioUltimaModificacion { get; set; }

    public string FcIpultimaModificacion { get; set; }

    public string FcToken { get; set; }
}