// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTickets.Entities.Entities;

public partial class RequerimientosUsuario
{
    public int FiIdusuario { get; set; }

    public string FcNombreCompleto { get; set; }

    public string FcNombreCorto { get; set; }

    public string FcUsuarioAcceso { get; set; }

    public string FcPassword { get; set; }

    public string FcCorreoElectronico { get; set; }

    public int FiIddepartamento { get; set; }

    public byte FiIdtipoUsuario { get; set; }

    public string FcToken { get; set; }
}