// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTickets.Entities.Entities;

public partial class RequerimientosCatalogoCategoria
{
    public int FiIdcategoriaDesarrollo { get; set; }

    public string FcDescripcionCategoria { get; set; }

    public string FcToken { get; set; }
}