// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTickets.Entities.Entities;

public partial class RequerimientosCatalogoTipodeRequerimiento
{
    public int FiIdtipoRequerimiento { get; set; }

    public string FcTipoRequerimiento { get; set; }

    public string FcToken { get; set; }
}