// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTickets.Entities.Entities;

public partial class RpaTotal
{
    public string Empresa { get; set; }

    public string Razon { get; set; }

    public string Rtn { get; set; }

    public string Direc { get; set; }

    public string Telefono { get; set; }

    public string Identidad { get; set; }

    public string Nombrecomp { get; set; }

    public string Telefonoem { get; set; }

    public string Celularemp { get; set; }

    public string Direccione { get; set; }
}