// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTickets.Entities.Entities;

public partial class Sheet1
{
    public string RazonDeLaEmpresa { get; set; }

    public string NombreDeLaEmpresa { get; set; }
}