// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTickets.Entities.Entities;

public partial class SieavancesCcme
{
    public string FcSegmento { get; set; }

    public decimal? FiMeta { get; set; }

    public decimal? FiRecuperado { get; set; }
}