// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTickets.Entities.Entities;

public partial class TblCneRSexo
{
    public short CodigoSexo { get; set; }

    public string DescripcionSexo { get; set; }
}