// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTickets.Entities.Entities;

public partial class TblCneMCensoNacional
{
    public string NumeroIdentidad { get; set; }

    public string PrimerNombre { get; set; }

    public string SegundoNombre { get; set; }

    public string PrimerApellido { get; set; }

    public string SegundoApellido { get; set; }

    public short? CodigoSexo { get; set; }

    public string FechaNacimiento { get; set; }

    public short? CodigoDepartamentoDomicilio { get; set; }

    public short? CodigoMunicipioDomicilio { get; set; }

    public short? CodigoAldea { get; set; }

    public short? CodigoLugarPoblado { get; set; }

    public short? CodigoArea { get; set; }

    public short? CodigoSectorElectoral { get; set; }

    public string CodigoHabilInhabil { get; set; }

    public short? CodigoCentroVotacion { get; set; }

    public string CodigoEstadoTarjeta { get; set; }

    public short? NumeroMesa { get; set; }

    public short? NumeroLinea { get; set; }
}