// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTickets.Entities.Entities;

public partial class TblDpgeMCentroVotacion
{
    public short CodigoDepartamento { get; set; }

    public short CodigoMunicipio { get; set; }

    public short CodigoArea { get; set; }

    public short CodigoSectorElectoral { get; set; }

    public short CodigoCentroVotacion { get; set; }

    public string NombreCentro { get; set; }
}