// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTickets.Entities.Entities;

public partial class TblDpgeRArea
{
    public short CodigoArea { get; set; }

    public string DescripcionArea { get; set; }
}