// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTickets.Entities.Entities;

public partial class TblDpgeAMunicipio
{
    public short CodigoDepartamento { get; set; }

    public short CodigoMunicipio { get; set; }

    public string NombreMunicipio { get; set; }
}