// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTickets.Entities.Entities;

public partial class Telefono
{
    public string FcIdentidad { get; set; }

    public string FcTelefonos { get; set; }
}