// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTickets.Entities.Entities;

public partial class TutorialesVideo
{
    public int FiIdvideo { get; set; }

    public string FcDescripcionVideo { get; set; }

    public int? FiIdarea { get; set; }

    public string FcUrl { get; set; }

    public string FcNombreArchivo { get; set; }

    public DateTime? FdFechaCreado { get; set; }

    public string FcUsuarioCreador { get; set; }

    public int? FiOrden { get; set; }

    public bool? FbActivo { get; set; }
}