// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaTickets.Entities.Entities;

public partial class Xbase2019
{
    public string Empresa { get; set; }

    public string Rtn { get; set; }

    public string Tel1 { get; set; }

    public string Tel2 { get; set; }

    public string Tel3 { get; set; }

    public string Direccion { get; set; }

    public string Ident { get; set; }

    public string Empleado { get; set; }

    public double? Salario { get; set; }

    public string TelPerson { get; set; }

    public string Departamen { get; set; }

    public string Municipio { get; set; }

    public string Aldea { get; set; }

    public string Caserio { get; set; }

    public string Colonia { get; set; }

    public string Avenida { get; set; }

    public string Calle { get; set; }
}