// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Jojo.Entities.Entities
{
    public partial class tbCategorias
    {
        public tbCategorias()
        {
            tbProductos = new HashSet<tbProductos>();
        }

        public int cate_Id { get; set; }
        public string cate_Descripcion { get; set; }
        public int cate_UserCrea { get; set; }
        public DateTime cate_FechaCreacion { get; set; }
        public int? cate_UserModifica { get; set; }
        public DateTime? cate_FechaModificacion { get; set; }
        public bool? cate_Estado { get; set; }

        public virtual tbUsuarios cate_UserCreaNavigation { get; set; }
        public virtual tbUsuarios cate_UserModificaNavigation { get; set; }
        public virtual ICollection<tbProductos> tbProductos { get; set; }
    }
}