// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace Jojo.Entities.Entities
{
    public partial class tbPantallasPorRol
    {
        public int pantrol_Id { get; set; }
        public int? role_Id { get; set; }
        public int? pant_Id { get; set; }
        public bool? pantrol_Estado { get; set; }
        public int? pantrol_UserCrea { get; set; }
        public DateTime? pantrol_FechaCrea { get; set; }
        public int? pantrol_UserModifica { get; set; }
        public DateTime? pantrol_FechaModifica { get; set; }


        [Display(Name = "Pantalla Nombre")]
        [NotMapped]
        public string pant_Nombre { get; set; }
        [Display(Name = "Identificador")]
        [NotMapped]
        public string pant_Identificador { get; set; }
        [Display(Name = "Link")]
        [NotMapped]
        public string pant_href { get; set; }

        public virtual tbPantallas pant { get; set; }
        public virtual tbUsuarios pantrol_UserCreaNavigation { get; set; }
        public virtual tbUsuarios pantrol_UserModificaNavigation { get; set; }
        public virtual tbRoles role { get; set; }
    }
}