// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace Jojo.Entities.Entities
{
    public partial class tbUsuarios
    {
        public tbUsuarios()
        {
            Inverseuser_UserCreaNavigation = new HashSet<tbUsuarios>();
            Inverseuser_UserModificaNavigation = new HashSet<tbUsuarios>();
            tbCategoriascate_UserCreaNavigation = new HashSet<tbCategorias>();
            tbCategoriascate_UserModificaNavigation = new HashSet<tbCategorias>();
            tbClientesclie_UserCreaNavigation = new HashSet<tbClientes>();
            tbClientesclie_UserModificaNavigation = new HashSet<tbClientes>();
            tbDepartamentosdept_UserCreaNavigation = new HashSet<tbDepartamentos>();
            tbDepartamentosdept_UserModificaNavigation = new HashSet<tbDepartamentos>();
            tbEmpleadosempl_UserCreaNavigation = new HashSet<tbEmpleados>();
            tbEmpleadosempl_UserModificaNavigation = new HashSet<tbEmpleados>();
            tbEstadosCivilesestc_UserCreaNavigation = new HashSet<tbEstadosCiviles>();
            tbEstadosCivilesestc_UserModificaNavigation = new HashSet<tbEstadosCiviles>();
            tbFacturasDetallesfacd_UserCreaNavigation = new HashSet<tbFacturasDetalles>();
            tbFacturasDetallesfacd_UserModificaNavigation = new HashSet<tbFacturasDetalles>();
            tbFacturasfact_UserCreaNavigation = new HashSet<tbFacturas>();
            tbFacturasfact_UserModificaNavigation = new HashSet<tbFacturas>();
            tbMunicipiosmuni_UserCreaNavigation = new HashSet<tbMunicipios>();
            tbMunicipiosmuni_UserModificaNavigation = new HashSet<tbMunicipios>();
            tbPantallasPorRolpantrol_UserCreaNavigation = new HashSet<tbPantallasPorRol>();
            tbPantallasPorRolpantrol_UserModificaNavigation = new HashSet<tbPantallasPorRol>();
            tbPantallaspant_UserCreaNavigation = new HashSet<tbPantallas>();
            tbPantallaspant_UserModificaNavigation = new HashSet<tbPantallas>();
            tbProductosprod_UserCreaNavigation = new HashSet<tbProductos>();
            tbProductosprod_UserModificaNavigation = new HashSet<tbProductos>();
            tbProveedoresprov_UserCreaNavigation = new HashSet<tbProveedores>();
            tbProveedoresprov_UserModificaNavigation = new HashSet<tbProveedores>();
            tbRolesrole_UserCreaNavigation = new HashSet<tbRoles>();
            tbRolesrole_UserModificaNavigation = new HashSet<tbRoles>();
            tbSucursalessucu_UserCreaNavigation = new HashSet<tbSucursales>();
            tbSucursalessucu_UserModificaNavigation = new HashSet<tbSucursales>();
        }

        [Display(Name = "Id")]
        public int user_Id { get; set; }
        [Display(Name = "Nombre de Usuario")]
        public string user_NombreUsuario { get; set; }
        [Display(Name = "Empleado")]
        public string NombreEmpleado { get; set; }
        [Display(Name = "Contraseña")]
        public string user_Contraseña { get; set; }
        [Display(Name = "Admin")]
        public bool? user_Admin { get; set; }
        [Display(Name = "Admin")]
        public string EsAdmin { get; set; }
        [Display(Name = "Rol")]
        public int? role_Id { get; set; }
        [Display(Name = "Estado")]
        public bool? user_Estado { get; set; }
        [Display(Name = "Usuario Creador")]
        public int? user_UserCrea { get; set; }
        [Display(Name = "Fecha Creación")]
        public DateTime? user_FechaCrea { get; set; }
        [Display(Name = "Ultimo Usuario Modificador")]
        public int? user_UserModifica { get; set; }
        [Display(Name = "Ultima Fecha Modificacion")]
        public DateTime? user_FechaModifica { get; set; }

        public int empl_Id { get; set; }


        public string empl_Nombres { get; set; }
        public string empl_Apellidos { get; set; }
        [Display(Name = "Usuario Creador")]
        public string empl_Crea { get; set; }
        [Display(Name = "Ultimo Usuario Modificador")]
        public string empl_Modifica { get; set; }

        [Display(Name = "Admin")]
        public string Es_Admin { get; set; }
        [Display(Name = "Rol")]
        public string role_Descripcion { get; set; }



        public virtual tbEmpleados empl { get; set; }
        public virtual tbRoles role { get; set; }
        public virtual tbUsuarios user_UserCreaNavigation { get; set; }
        public virtual tbUsuarios user_UserModificaNavigation { get; set; }
        public virtual ICollection<tbUsuarios> Inverseuser_UserCreaNavigation { get; set; }
        public virtual ICollection<tbUsuarios> Inverseuser_UserModificaNavigation { get; set; }
        public virtual ICollection<tbCategorias> tbCategoriascate_UserCreaNavigation { get; set; }
        public virtual ICollection<tbCategorias> tbCategoriascate_UserModificaNavigation { get; set; }
        public virtual ICollection<tbClientes> tbClientesclie_UserCreaNavigation { get; set; }
        public virtual ICollection<tbClientes> tbClientesclie_UserModificaNavigation { get; set; }
        public virtual ICollection<tbDepartamentos> tbDepartamentosdept_UserCreaNavigation { get; set; }
        public virtual ICollection<tbDepartamentos> tbDepartamentosdept_UserModificaNavigation { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleadosempl_UserCreaNavigation { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleadosempl_UserModificaNavigation { get; set; }
        public virtual ICollection<tbEstadosCiviles> tbEstadosCivilesestc_UserCreaNavigation { get; set; }
        public virtual ICollection<tbEstadosCiviles> tbEstadosCivilesestc_UserModificaNavigation { get; set; }
        public virtual ICollection<tbFacturasDetalles> tbFacturasDetallesfacd_UserCreaNavigation { get; set; }
        public virtual ICollection<tbFacturasDetalles> tbFacturasDetallesfacd_UserModificaNavigation { get; set; }
        public virtual ICollection<tbFacturas> tbFacturasfact_UserCreaNavigation { get; set; }
        public virtual ICollection<tbFacturas> tbFacturasfact_UserModificaNavigation { get; set; }
        public virtual ICollection<tbMunicipios> tbMunicipiosmuni_UserCreaNavigation { get; set; }
        public virtual ICollection<tbMunicipios> tbMunicipiosmuni_UserModificaNavigation { get; set; }
        public virtual ICollection<tbPantallasPorRol> tbPantallasPorRolpantrol_UserCreaNavigation { get; set; }
        public virtual ICollection<tbPantallasPorRol> tbPantallasPorRolpantrol_UserModificaNavigation { get; set; }
        public virtual ICollection<tbPantallas> tbPantallaspant_UserCreaNavigation { get; set; }
        public virtual ICollection<tbPantallas> tbPantallaspant_UserModificaNavigation { get; set; }
        public virtual ICollection<tbProductos> tbProductosprod_UserCreaNavigation { get; set; }
        public virtual ICollection<tbProductos> tbProductosprod_UserModificaNavigation { get; set; }
        public virtual ICollection<tbProveedores> tbProveedoresprov_UserCreaNavigation { get; set; }
        public virtual ICollection<tbProveedores> tbProveedoresprov_UserModificaNavigation { get; set; }
        public virtual ICollection<tbRoles> tbRolesrole_UserCreaNavigation { get; set; }
        public virtual ICollection<tbRoles> tbRolesrole_UserModificaNavigation { get; set; }
        public virtual ICollection<tbSucursales> tbSucursalessucu_UserCreaNavigation { get; set; }
        public virtual ICollection<tbSucursales> tbSucursalessucu_UserModificaNavigation { get; set; }
    }
}