// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class AgenciasDireccione
{
    public string FcCentrodeCosto { get; set; }

    public string FcCiudad { get; set; }

    public string FcDepartamento { get; set; }
}