// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class AgenciasMaestro
{
    public int FiIdagencia { get; set; }

    public string FcNombreAgencia { get; set; }

    public string FcCentrodeCosto { get; set; }

    public string FcCentrodeCostoMaestro { get; set; }

    public string FcDireccionFisica { get; set; }

    public short FiIdbarrioColonia { get; set; }

    public short FiIdciudad { get; set; }

    public short FiIddepartamento { get; set; }

    public short FiIdpais { get; set; }

    public byte FiTipoAgencia { get; set; }

    public short FiIdcanal { get; set; }

    public byte FiEstadoActual { get; set; }

    public string FcCuentaDesembolsos { get; set; }

    public string FcCuentaCajaOperativa { get; set; }

    public string FcCuentaCajaPuente { get; set; }

    public DateTime FdAltaAgencia { get; set; }

    public int FiIdusuario { get; set; }

    public DateTime? FdBajaAgencia { get; set; }

    public DateTime? FdUltimaActualizacion { get; set; }

    public byte? FiInstalacionGps { get; set; }

    public virtual ICollection<ContratistaSolicitudInstalacion> ContratistaSolicitudInstalacions { get; set; } = new List<ContratistaSolicitudInstalacion>();
}