// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class BasesCallCenterCatalogoGestione
{
    public int FiIdgestion { get; set; }

    public string FcGestion { get; set; }

    public string FcToken { get; set; }
}