// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class BasesCallCenterBitacora
{
    public int FiIdbitacora { get; set; }

    public int FiIdagente { get; set; }

    public int FiIdcliente { get; set; }

    public string FcTelefonoContacto { get; set; }

    public int FiIdgestion { get; set; }

    public string FcComentarioGestion { get; set; }

    public DateTime? FdFechaGestion { get; set; }

    public string FcToken { get; set; }
}