// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class CatalogoProveedore
{
    public int FiIdproveedor { get; set; }

    public string FcNombre { get; set; }

    public int? FiTipoPersona { get; set; }

    public string FcRtn { get; set; }

    public string FcContacto { get; set; }

    public int? FiCodPais { get; set; }

    public short? FiCodDepartamento { get; set; }

    public int? FiCodCiudad { get; set; }

    public int? FiCodAldeaPoblado { get; set; }

    public string FcDireccion1 { get; set; }

    public string FcDireccion2 { get; set; }

    public string FcTelefono { get; set; }

    public string FcTelefonoMovil { get; set; }

    public string FcCorreoElectronico { get; set; }

    public int? FiIdcuentaPorPagar { get; set; }

    public string FcCai { get; set; }

    public DateTime? FdFechaLimiteEmisionFactura { get; set; }

    public string FcPrefijoFactura { get; set; }

    public int? FiRangoInicialFactura { get; set; }

    public int? FcRangoFinalFactura { get; set; }

    public string FcComentario { get; set; }

    public int? FiDiasLimiteCredito { get; set; }

    public int? FiIdusuarioCreacion { get; set; }

    public DateTime? FdFechaCreacion { get; set; }

    public int? FiIdusuarioUltimaModificacion { get; set; }

    public DateTime? FdFechaUltimaModificacion { get; set; }

    public bool? FbEstadoProveedor { get; set; }

    public string FcToken { get; set; }

    public virtual ICollection<ProductosMovimientosMaestro> ProductosMovimientosMaestros { get; set; } = new List<ProductosMovimientosMaestro>();
}