// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class CatalogoCiudade
{
    public short FiIdciudad { get; set; }

    public string FcCiudad { get; set; }
}