// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class CatalogoDocumentosRequeridosDetalle
{
    public byte FiIddocumentosRequeridos { get; set; }

    public short FiIdordenDocumentos { get; set; }

    public string FcDescripcionDocumento { get; set; }
}