// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class CatalogoOrigendelCliente
{
    public string FcOrigenPrimario { get; set; }

    public string FcOrigenSecundario { get; set; }

    public byte FiLlevaReferencia { get; set; }

    public byte FiHabilitado { get; set; }
}