// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class CatalogoColoniasFalsa
{
    public int FiIdcoloniaFalsa { get; set; }

    public string FcDescripcion { get; set; }
}