// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class CatalogoModelo
{
    public byte FiIdmarca { get; set; }

    public byte FiIdmodelo { get; set; }

    public string FcModelo { get; set; }

    public DateTime FdFechaCreacion { get; set; }

    public int FiIdusuarioCreacion { get; set; }

    public DateTime FdFechaUltimaModificacion { get; set; }

    public int FiIdusuarioUltimaModificacion { get; set; }

    public string FcToken { get; set; }
}