// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class CatalogoParentesco
{
    public int FiIdparentesco { get; set; }

    public string FcDescripcionParentesco { get; set; }

    public int FiIdtipoDeParentesco { get; set; }
}