// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class CatalogoFondo
{
    public int FiIdfondo { get; set; }

    public string FcRazonSocial { get; set; }

    public string FcNombreComercial { get; set; }

    public string FcRtnempresa { get; set; }

    public string FcCiudadDomiciliada { get; set; }

    public string FcDepartamentoDomiciliada { get; set; }

    public string FcBarrio { get; set; }

    public string FcTelefono { get; set; }

    public string FcEmail { get; set; }

    public string FcRegistroMercantil { get; set; }

    public string FcNumeroFolio { get; set; }

    public int? FiIdrepresentanteLegal { get; set; }

    public string FcConstitucionFondo { get; set; }

    public string FcUrlLogo { get; set; }

    public byte FiIdtipodeFondo { get; set; }

    public byte? FiEstadodelFondo { get; set; }

    public string FcNombredelFondo { get; set; }
}