// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class CatalogoTipoDeProductoContable
{
    public int FiIdTipoDeProductoContable { get; set; }

    public string FcDescripcion { get; set; }

    public string FcCuentaContable { get; set; }

    public string FcToken { get; set; }

    public virtual ICollection<ProductosMaestro> ProductosMaestros { get; set; } = new List<ProductosMaestro>();
}