// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class CatalogoRepresentantesLegale
{
    public int FiIdrepresentanteLegal { get; set; }

    public string FcNombreCompleto { get; set; }

    public string FcIdentidad { get; set; }

    public int FiIdestadoCivil { get; set; }

    public int FiIdnacionalidad { get; set; }

    public string FcProfesion { get; set; }

    public string FcCiudadDomicilio { get; set; }

    public string FcDepartamentoDomicilio { get; set; }

    public string FcBarrio { get; set; }
}