// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class CatalogoOlt
{
    public int FiIdolt { get; set; }

    public string FcDescripcionOlt { get; set; }

    public string FcDireccion { get; set; }

    public string FcLatitude { get; set; }

    public string FcLongitud { get; set; }

    public string FcIpolt { get; set; }

    public DateTime FdFechaCreacion { get; set; }

    public int FiIdusuarioCreacion { get; set; }

    public DateTime? FdFechaModificacion { get; set; }

    public int? FiIdusuarioModificacion { get; set; }
}