// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class CatalogoPerfil
{
    public short FiIdproducto { get; set; }

    public short FiIdperfil { get; set; }

    public string FcDescripcionPerfil { get; set; }

    public short FiTipodeIngresos { get; set; }

    public short FiScoreMinimo { get; set; }

    public short FiScoreMaximo { get; set; }

    public short FiEdadMinima { get; set; }

    public short FiEdadMaxima { get; set; }

    public short FiIhssminimo { get; set; }

    public short FiIhssmaximo { get; set; }

    public short FiAntiguedadEquifaxMinimo { get; set; }

    public short FiAntiguedadEquifaxMaximo { get; set; }

    public short FiAntiguedadLaboralMinimo { get; set; }

    public short FiAntiguedadLaboralMaximo { get; set; }

    public short FiAntiguedadNegocioMinimo { get; set; }

    public short FiAntiguedadNegocioMaximo { get; set; }

    public decimal FnOblicacionesMinimo { get; set; }

    public decimal FnOblicacionesMaximo { get; set; }

    public decimal FnIngresosMinimo { get; set; }

    public decimal FnIngresosMaximo { get; set; }

    public byte FiCasaPropia { get; set; }

    public byte FiPermisoOperacion { get; set; }

    public byte FiMaquilaCallcenter { get; set; }

    public byte FiGuardiaSeguridad { get; set; }

    public byte FiResolucionAnalisis { get; set; }

    public byte FiLleveYa { get; set; }

    public byte FiTipodeCalculoCapcidaddePago { get; set; }

    public decimal FnMaximoMontoPrestamo { get; set; }

    public string FcDescripcionTipodeCliente { get; set; }

    public string FcMensajeObservaciones { get; set; }

    public string FcDescripcionRequerimientos { get; set; }

    public byte FiIddocumentosRequeridos { get; set; }
}