// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class CatalogoPuesto
{
    public short FiIdpuesto { get; set; }

    public string FcDescripcion { get; set; }

    public byte FiTipoUsuario { get; set; }

    public byte FiEstado { get; set; }

    public byte FiOperaEfectivo { get; set; }

    public byte FiOperaDocumentos { get; set; }
}