// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class CatalogoConfiguracione
{
    public int FiIdConfiguraciones { get; set; }

    public string FcNombreLlave { get; set; }

    public string FcValorLlave { get; set; }
}