// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class CatalogoTipoPersona
{
    public int FiIdtipoPersona { get; set; }

    public string FcDescripcion { get; set; }

    public int? FiIdusuarioCreacion { get; set; }

    public DateTime? FdFechaCreacion { get; set; }

    public int? FiUsuarioModificacion { get; set; }

    public DateTime? FdFechaModificacion { get; set; }
}