// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class CatalogoPaquete
{
    public int FiIdgrupoProducto { get; set; }

    public string FcCampoPaquete { get; set; }

    public string FcNombrePaquete { get; set; }
}