// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class CatalogoRazonDeclinar
{
    public int FiIdrazon { get; set; }

    public string FcRazonDelcinar { get; set; }

    public int? FiEstado { get; set; }
}