// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class ClientesServiciosBitacora
{
    public int? FiIdcliente { get; set; }

    public int? FiIdsolicitud { get; set; }

    public DateTime? FdFechadeMovimiento { get; set; }

    public byte? FiIdestadodeConexion { get; set; }

    public string FcComentario { get; set; }

    public string FcInstruccionWebService { get; set; }

    public string FcRespuestaWebService { get; set; }

    public string FcInstruccionServicioMensajeria { get; set; }

    public string FcRespuestaServicioMensajeria { get; set; }

    public int? FiIdusuario { get; set; }

    public int? FiIdtransaccion { get; set; }

    public string FcToken { get; set; }
}