// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class ClientesPerfil
{
    public int FiIdequifax { get; set; }

    public string FcIdentidad { get; set; }

    public short FiIdperfilCliente { get; set; }

    public decimal FnIngresos { get; set; }

    public byte FiOcupacion { get; set; }

    public string FcTelefono { get; set; }

    public short FiCiudadResidencia { get; set; }

    public int FiIdproducto { get; set; }

    public byte FiMaquilaCallCenter { get; set; }

    public byte FiCasaPropia { get; set; }

    public byte FiEsGuardiadeSeguridad { get; set; }

    public byte FiAntiguedadRequerida { get; set; }

    public byte FiPermisodeOperacionVigente { get; set; }
}