// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class ClienteReferenciaRespuesta
{
    public int FiIdrespuesta { get; set; }

    public int? FiDreferencia { get; set; }

    public string FcRespuesta1 { get; set; }

    public string FcRespuesta2 { get; set; }

    public string FcRespuesta3 { get; set; }

    public int? FbAceptoSerReferencia { get; set; }

    public int? FiRespuestasAcertadas { get; set; }

    public int? FiRespuestasNoAcertadas { get; set; }
}