// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class ClientesMovilLogin
{
    public int FiIdunico { get; set; }

    public int FiIdcuentaFamiliar { get; set; }

    public int? FiIdcliente { get; set; }

    public string FcUsuarioAcceso { get; set; }

    public string FcPassword { get; set; }

    public string FcNombreUsuario { get; set; }

    public string FcNmbreCorto { get; set; }

    public string FcTelefono { get; set; }

    public string FcUrlfotoPersonalizda { get; set; }

    public byte FiTipodeUsuario { get; set; }

    public DateTime FdFechaCreacion { get; set; }

    public DateTime? FdFechaPrimerAcceso { get; set; }

    public DateTime? FdFechaUltimoAcceso { get; set; }

    public string FcToken { get; set; }
}