// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class ClientesReferidosCredito
{
    public int FiIdclienteReferido { get; set; }

    public string FcNombreReferido { get; set; }

    public string FcNumeroTelefono { get; set; }

    public int FiIdequifaxClienteReferente { get; set; }

    public DateTime FdFechaCreacion { get; set; }

    public DateTime FdFechaVencimiento { get; set; }
}