// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class ClienteReferencium
{
    public int FiIdreferencia { get; set; }

    public int FiIdequifax { get; set; }

    public string FcNombreCompletoReferencia { get; set; }

    public string FcLugarTrabajoReferencia { get; set; }

    public string FcTelefonoReferencia { get; set; }

    public int FiIdparentescoReferencia { get; set; }

    public int? FiAnalistaComentario { get; set; }

    public string FcComentarioDeptoCredito { get; set; }

    public bool? FbSinComunicacion { get; set; }

    public DateTime? FdFechaAnalisis { get; set; }

    public int? FbReferenciaActivo { get; set; }

    public int FiIdusuarioCrea { get; set; }

    public DateTime FdFechaCrea { get; set; }

    public bool? FbAceptoSerRefencia { get; set; }

    public int? FiAceptoSerRefencia { get; set; }

    public string FcApellidoReferencia { get; set; }

    public int? FiIdClientesMaestro { get; set; }

    public int? FiNumeroConsecutivoCliente { get; set; }
}