// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class ClientesLinksdePago
{
    public string FcIdentidad { get; set; }

    public int FiNumerodeCuota { get; set; }

    public DateTime FdFechaMaximoLink { get; set; }

    public string FcLinkdePago { get; set; }

    public int FiIdusuarioCreador { get; set; }

    public DateTime FdFechaCreacion { get; set; }

    public int FiIdusuarioModificador { get; set; }

    public DateTime FdFechaModificacion { get; set; }

    public string FcToken { get; set; }
}