// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class ClientesMaestro
{
    public int FiIdequifax { get; set; }

    public string FcLugarTrabajo { get; set; }

    public string FcLugarVive { get; set; }

    public int FiIdClientesMaestro { get; set; }

    public int? FiEstadoMensaje { get; set; }

    public int? FiEstadoProductoServicio { get; set; }

    public int? FiEstadoCivil { get; set; }

    public bool? FbTieneHijos { get; set; }

    public string FcCiudad { get; set; }

    public string FcDireccionDetallada { get; set; }

    public string FcProfesion { get; set; }

    public string FcCorreo { get; set; }

    public string FcGeolocalizacion { get; set; }

    public int? FiCodDepartamento { get; set; }

    public int? FiCodMunicipio { get; set; }

    public int? FiCodPoblado { get; set; }

    public int? FiCodColonia { get; set; }

    public string FiTipoVivienda { get; set; }

    public int? FiUbicacionGuardada { get; set; }

    public int? FcDiaPago { get; set; }

    public int? FiRangoSalarial { get; set; }

    public int? FiAntiguedadLaboral { get; set; }

    public int? FiNumeroConsecutivoCliente { get; set; }

    public bool? FbEsEditar { get; set; }
}