// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class ClientesServiciosBitacorasConexione
{
    public int FiIdbitacora { get; set; }

    public int FiIdcliente { get; set; }

    public int FiIdusuarioSolicitante { get; set; }

    public int FiIdtransaccionAbono { get; set; }

    public string FcContratodeConexion { get; set; }

    public byte FiIdtipodeProceso { get; set; }

    public byte FiIdestadoProceso { get; set; }

    public DateTime FdFechaSolicitud { get; set; }

    public DateTime? FdFechaEjecucion { get; set; }

    public string FcRespuestaServicio { get; set; }

    public int FiIdintentos { get; set; }

    public string FcToken { get; set; }
}