// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class ContratistaMaestro
{
    public int FiIdcontratista { get; set; }

    public int? FiIdusuario { get; set; }

    public string FcNombreEmpresa { get; set; }

    public int? FiIdagencia { get; set; }

    public string FcNombreEncargado { get; set; }

    public string FcTelefono { get; set; }

    public string FcCorreoElectronico { get; set; }

    public string FcRtnEmpresa { get; set; }

    public string FcDireccion { get; set; }
}