// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class ContratistaSolicitudInstalacionDetalleCodigoBarra
{
    public int FiIdsolicitudCodigoBarras { get; set; }

    public int? FiIdcontratistaSolicitudInstalacionDetalle { get; set; }

    public int? FiIdmoviemiento { get; set; }

    public bool? FbEstadoInstalacionCodigoBarra { get; set; }
}