// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class ContratistaSolicitudInstalacionDetalle
{
    public int FiIdcontratistaSolicitudInstalacionDetalle { get; set; }

    public int? FiIdcontratistaSolicitudInstalacion { get; set; }

    public int? FiIdproducto { get; set; }

    public int? FiIdinventario { get; set; }

    public decimal? FnCantidad { get; set; }

    public string FcSerie { get; set; }

    public string FcMac { get; set; }
}