// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class ContratistaSolicitudInstalacion
{
    public int FiIdcontratistaSolicitud { get; set; }

    public int? FiIdcontratista { get; set; }

    public int? FiIdsolicitud { get; set; }

    public int? FiIdequifax { get; set; }

    public int? FiIdpaquete { get; set; }

    public int? FiIdagenciaInstalacion { get; set; }

    public int? FiIdagenciaContratista { get; set; }

    public int? FiNoOrden { get; set; }

    public int? FiIdusuarioCreador { get; set; }

    public DateTime? FdFechaInstalacion { get; set; }

    public string FcComentario { get; set; }

    public int? FiIdestadoInstalacion { get; set; }

    public int? FiIdtecnicoAsignado { get; set; }

    public decimal? FnMetrosFibra { get; set; }

    public int? FiQracceso { get; set; }

    public int? FiIdubicacion { get; set; }

    public DateTime? FdFechaInstalacionInicio { get; set; }

    public DateTime? FdFechaInstalacionFinal { get; set; }

    public string FcCodigoCliente { get; set; }

    public string FcNumeroOrdenCfeus { get; set; }

    public string FcComentarioInstalacion { get; set; }

    public int? FiIdtipoSolicitud { get; set; }

    public int? FiIdinventarioMovimientoMaestro { get; set; }

    public DateTime? FdFechaInstalacionAsignada { get; set; }

    public virtual AgenciasMaestro FiIdagenciaInstalacionNavigation { get; set; }

    public virtual InventarioMovimientoMaestro FiIdinventarioMovimientoMaestroNavigation { get; set; }
}