// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class CredPrecalificadoOrigenCliente
{
    public string FcIdentidad { get; set; }

    public int FiIdusuario { get; set; }

    public DateTime FdFechaCreacion { get; set; }

    public DateTime FdUltimaActualicion { get; set; }

    public string FcOrigenPrimario { get; set; }

    public string FcOrigenSecundario { get; set; }

    public string FcReferenciaOrigen { get; set; }
}