// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class DevolucionMaestro
{
    public int FiIddevolucionMaestro { get; set; }

    public int FiIdubicacionInicial { get; set; }

    public int FiIdubicacionDestino { get; set; }

    public int FiIdusuarioCreado { get; set; }

    public DateTime FdFechaCreacion { get; set; }

    public int FiIdusuarioUltimaModificacion { get; set; }

    public DateTime FdFechaUltimaModificacion { get; set; }

    public int FiFirma { get; set; }

    public string FcDocumentoFirma { get; set; }

    public int FiEstadoInventairoMovimientoMaestro { get; set; }

    public string FcToken { get; set; }

    public string FcMotivoDevolucion { get; set; }

    public int? FiIdinventarioMovimientoMaestro { get; set; }
}