// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class DevolucionDetalle
{
    public int FiIddevolucionDetalle { get; set; }

    public int FiIddevolucionMaestro { get; set; }

    public string FcCodigoSerie1 { get; set; }

    public string FcCodigoSerie2 { get; set; }

    public decimal FnCantidad { get; set; }

    public string FcDescripcion { get; set; }

    public int FiIdusuarioCreado { get; set; }

    public DateTime FdFechaCreacion { get; set; }

    public string FcToken { get; set; }

    public int? FiIdproducto { get; set; }

    public int? FiIdinventarioMovimientoDetalle { get; set; }
}