// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class EmailTemplate
{
    public int FiIdemailTemplate { get; set; }

    public string FcDescriptionEmailTemplate { get; set; }

    public string FcEmailSubject { get; set; }

    public string FcEmailBody { get; set; }

    public string FcEmailTitle { get; set; }

    public string FcEmailFooter { get; set; }

    public bool FbEmailTemplateActive { get; set; }

    public string FcEmailAttachmentName { get; set; }
}