// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class EmpresasMaestro
{
    public int FiIdempresa { get; set; }

    public string FcNombreComercial { get; set; }

    public string FcRazonSocial { get; set; }

    public string FcRtn { get; set; }

    public string FcDireccionExacta { get; set; }

    public string FcCiudadDomiciliada { get; set; }

    public string FcTelefono { get; set; }

    public string FcCorreoElectronico { get; set; }

    public string FcCai { get; set; }

    public DateTime? FdFechaModificado { get; set; }
}