// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class EquifaxCliente
{
    public int FiIdequifax { get; set; }

    public string FcIdentidad { get; set; }

    public string FcNombre { get; set; }

    public DateTime? FdFechaNacimiento { get; set; }

    public byte FiTieneHistorialEquifax { get; set; }

    public byte FiCargaInicial { get; set; }

    public short FiScorePromedio { get; set; }

    public short FiScoreActual { get; set; }

    public DateTime FdFechaPrimerConsulta { get; set; }

    public DateTime FdFechaUltimaActualizacionEquifax { get; set; }

    public short FiIdapp { get; set; }

    public string FcCentrodeCostoConsultante { get; set; }

    public int FiIdusuario { get; set; }

    public string FcCentrodeCostoAsignado { get; set; }

    public int FiIdusuarioAsignado { get; set; }

    public DateTime FdFechaUltimaConsulta { get; set; }

    public int FiIdusuarioUltimaConsulta { get; set; }

    public decimal FnIngresos { get; set; }

    public byte FiOcupacion { get; set; }

    public string FcTelefono { get; set; }

    public short FcCiudadResidencia { get; set; }

    public DateTime? FdAntiguedadBuroEquifax { get; set; }

    public DateTime? FdAntiguedadBuroPrestadito { get; set; }

    public string FcArchivoXml { get; set; }

    public decimal FnCuotaBanca { get; set; }

    public decimal FnCuotaComercio { get; set; }

    public decimal FnCuotaTarjeta { get; set; }

    public decimal FnSaldoBanca { get; set; }

    public decimal FnSaldoComercio { get; set; }

    public decimal FnSaldoTarjeta { get; set; }

    public byte FiReglaCalculoCapacidad { get; set; }

    public byte FiResultadoPrecalificado { get; set; }

    public byte FiResultadoDetallePrecalificado { get; set; }

    public byte FiResolucionCreditos { get; set; }

    public int? FiIdusuarioCreditos { get; set; }

    public DateTime? FdResolucionCreditos { get; set; }

    public string FcObservacionesCreditos { get; set; }

    public byte? FiEstadoActualPrecalificado { get; set; }

    public int FiIdproducto { get; set; }

    public decimal FnMontoSeleccionado { get; set; }

    public short FiPlazoSeleccionado { get; set; }

    public decimal? FnMontoAprobado { get; set; }

    public short? FiPlazoAprobado { get; set; }

    public byte? FiResolucionGeneral { get; set; }

    public byte FiClienteCc { get; set; }

    public byte FiIhss { get; set; }

    public byte FiCne { get; set; }

    public byte FiCallCenter { get; set; }

    public byte FiMoraComunicaciones { get; set; }

    public byte FiMoraMayor { get; set; }

    public byte FiMoraMenor { get; set; }

    public byte FiMoraHistorica { get; set; }

    public byte FiSobregiro { get; set; }

    public byte FiIncobrable { get; set; }

    public byte FiIrrecuperable { get; set; }

    public byte FiJuridicoLegal { get; set; }

    public byte FiSaldosCastigados { get; set; }
}