// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class EquifaxInfoFiadore
{
    public int FiIdequifax { get; set; }

    public string FcIdentidad { get; set; }

    public string ViewId { get; set; }

    public string CandidateCorrelative { get; set; }

    public string ViewLength { get; set; }

    public string ViewReturnCode { get; set; }

    public string InfoPeriod { get; set; }

    public string ActualPeriod { get; set; }

    public string DebtorType { get; set; }

    public string OperationNumber { get; set; }

    public string RiskCategory { get; set; }

    public string Creditor { get; set; }

    public string MainDebtorTip { get; set; }

    public string MainDebtorRtn { get; set; }

    public string MainDebtorNii { get; set; }

    public string MainDebtorPas { get; set; }

    public string MainDebtorNce { get; set; }

    public string IdCreditor { get; set; }
}