// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class EquifaxScoreHistorico
{
    public int FiIdequifax { get; set; }

    public string FcIdentidad { get; set; }

    public string PeriodoActual { get; set; }

    public string PeriodoInformacion { get; set; }

    public byte TipoScore { get; set; }

    public decimal ValorScore { get; set; }

    public string Mensaje1 { get; set; }

    public string Mensaje2 { get; set; }

    public string Mensaje3 { get; set; }

    public string VectorProducto { get; set; }
}