// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class EquifaxCatalogoCapacidadePago
{
    public int FiIdcapacidaddepago { get; set; }

    public string FcDescripcionCapacidadePago { get; set; }

    public decimal FiPorcentajeCapacidadePago { get; set; }

    public short FiIdproducto { get; set; }
}