// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class EquifaxHighRisk
{
    public int FiIdequifax { get; set; }

    public string FcIdentidad { get; set; }

    public string InDate { get; set; }

    public string InMotivation { get; set; }

    public string Currency { get; set; }

    public string CurrencyType { get; set; }

    public string TotalDebtAmount { get; set; }

    public string ChangeFactor { get; set; }

    public string InfoDate { get; set; }

    public string ViewLength { get; set; }

    public string ViewReturnCode { get; set; }

    public string ViewId { get; set; }

    public string Creditor { get; set; }

    public string CandidateCorrelative { get; set; }

    public string IdCreditor { get; set; }
}