// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class EquifaxCatalogoScore
{
    public int FiIdproducto { get; set; }

    public string FcDescripcionProducto { get; set; }

    public short FiScoreMinimo { get; set; }
}