// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class EquifaxBitacoraWscoreFinanciero
{
    public short FiIdapp { get; set; }

    public string FcCentrodeCosto { get; set; }

    public int FiIdusuario { get; set; }

    public DateTime FdBitacora { get; set; }

    public string FcIdentidad { get; set; }

    public byte FiTipoMensaje { get; set; }

    public string FcMensajeProceso { get; set; }
}