// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class EquifaxDeucomer
{
    public int FiIdequifax { get; set; }

    public string FcIdentidad { get; set; }

    public string CreditType { get; set; }

    public string ActualPeriod { get; set; }

    public string CreditTypeCode { get; set; }

    public string InfoType { get; set; }

    public string LastDate { get; set; }

    public string AmountCurrencyType { get; set; }

    public string AmountCurrency { get; set; }

    public string GivedAmount { get; set; }

    public string NumberOfPayments { get; set; }

    public string PeorNivelDeucomer { get; set; }

    public string Referencia { get; set; }

    public string ViewId { get; set; }

    public string OpenningDate { get; set; }

    public string CancelationDate { get; set; }

    public string InfoSource { get; set; }

    public string InfoDate { get; set; }

    public string DebtCurrencyType { get; set; }

    public string DebtCurrency { get; set; }

    public string PaymentCurrencyType { get; set; }

    public string PaymentCurrency { get; set; }

    public string AccountStatus { get; set; }

    public string StatusDate { get; set; }

    public string DwellLevel { get; set; }

    public string DwellDate { get; set; }

    public string DwellCurrency { get; set; }

    public string DwellCurrencyType { get; set; }

    public string ViewLength { get; set; }

    public string InfoPeriod { get; set; }

    public string Debt { get; set; }

    public string PaymentValue { get; set; }

    public string DwellingDebt { get; set; }

    public string ViewReturnCode { get; set; }

    public string ChangeFactor { get; set; }

    public string Payway { get; set; }

    public string CandidateCorrelative { get; set; }

    public string IdInfoSource { get; set; }
}