// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class EquifaxGarantium
{
    public int FiIdequifaxGarantia { get; set; }

    public int FiIdequifax { get; set; }

    public string FcIdentidad { get; set; }

    public int FiIdproducto { get; set; }

    public int? FiIdsolicitud { get; set; }

    public decimal? FnValorProductoMn { get; set; }

    public decimal? FnValorProductoMe { get; set; }

    public decimal? FnPorcentajeImpuesto1 { get; set; }

    public decimal? FnPorcentajeImpuesto2 { get; set; }

    public string FcSerieProducto { get; set; }

    public int? FiIdMoneda { get; set; }

    public DateTime FdFechaCreacion { get; set; }

    public int FiIdusuarioCreador { get; set; }

    public DateTime? FdFechaModificacion { get; set; }

    public DateTime? FiIdusuarioModificacion { get; set; }

    public decimal? FnValorCuotaMensual { get; set; }

    public int? FiIdpaquete { get; set; }

    public string FcToken { get; set; }
}