// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class EquifaxHistoricoTardeudum
{
    public int FiIdequifax { get; set; }

    public string FcIdentidad { get; set; }

    public string NumeroReferencia { get; set; }

    public string ConteoHistoricoLoc { get; set; }

    public string ConteoHistoricoDol { get; set; }

    public string VectorCategoriasTar { get; set; }

    public string FechaApertura { get; set; }

    public string PeriodoActual { get; set; }

    public string PeriodoInformacionMasReciente { get; set; }

    public string Acreedor { get; set; }

    public string MorosidadHistorica { get; set; }

    public string IdAcreedor { get; set; }
}