// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class EquifaxConteosMoraBancaria24M
{
    public int FiIdequifax { get; set; }

    public string FcIdentidad { get; set; }

    public string PeriodoActual { get; set; }

    public string PeriodoInformacion { get; set; }

    public string UltimoPeriodoReportadoMora { get; set; }

    public string PeriodoReportadoMoraMasAntiguo { get; set; }

    public string FuenteInformacion { get; set; }

    public string Moneda { get; set; }

    public string DescripcionMoneda { get; set; }

    public short TotalAtrasos { get; set; }

    public short DiasMoraMaximo { get; set; }

    public short DiasMoraMinimo { get; set; }

    public decimal MayorSaldoMora { get; set; }

    public decimal MenorSaldoMora { get; set; }

    public short ConteosMora30 { get; set; }

    public short ConteosMora60 { get; set; }

    public short ConteosMora90 { get; set; }

    public short ConteosMora120 { get; set; }

    public short ConteosMora150 { get; set; }

    public short ConteosMora180 { get; set; }

    public string CategoriaRiesgo { get; set; }

    public string CodigoFuente { get; set; }
}