// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class EquifaxMorInfo
{
    public int FiIdequifax { get; set; }

    public string FcIdentidad { get; set; }

    public string InfoPeriod { get; set; }

    public string DwellDate { get; set; }

    public string Currency { get; set; }

    public string CurrencyType { get; set; }

    public string InfoDate { get; set; }

    public string Creditor { get; set; }

    public string InfoType { get; set; }

    public string DwellAmount { get; set; }

    public string DwellDays { get; set; }

    public string ChangeFactor { get; set; }

    public string ActualPeriod { get; set; }

    public string MorinfoMasReciente { get; set; }

    public string IdCreditor { get; set; }
}