// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class EquifaxSicom
{
    public int FiIdequifax { get; set; }

    public string FcIdentidad { get; set; }

    public string ViewId { get; set; }

    public string ViewReturnCode { get; set; }

    public string DwellDate { get; set; }

    public string Currency { get; set; }

    public short CurrencyType { get; set; }

    public short DwellDays { get; set; }

    public string InfoDate { get; set; }

    public string InfoType { get; set; }

    public string Creditor { get; set; }

    public short ViewLength { get; set; }

    public byte CandidateCorrelative { get; set; }

    public decimal DwellAmount { get; set; }

    public decimal ChangeFactor { get; set; }

    public string MoraMasReciente { get; set; }

    public string IdCreditor { get; set; }
}