// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class EquifaxDiasAtrasoConsolidado
{
    public int FiIdequifax { get; set; }

    public string FcIdentidad { get; set; }

    public string PeriodoActualBanca { get; set; }

    public string VectorDiasAtrasoBanca { get; set; }

    public string VectorSaldosMoraBanca { get; set; }

    public string PeriodoActualComercio { get; set; }

    public string VectorDiasAtrasoComercio { get; set; }

    public string VectorSaldosMoraComercio { get; set; }

    public string PeriodoActualTarjeta { get; set; }

    public string VectorDiasAtrasoTarjeta { get; set; }

    public string VectorSaldosMoraTarjeta { get; set; }
}