// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class EquifaxPrimeraReferenciaBandeudum
{
    public int FiIdequifax { get; set; }

    public string FcIdentidad { get; set; }

    public string ViewId { get; set; }

    public short CandidateCorrelative { get; set; }

    public short ViewLength { get; set; }

    public string ViewReturnCode { get; set; }

    public string ActualPeriod { get; set; }

    public string InfoPeriod { get; set; }

    public string ObligationType { get; set; }

    public string EconActivity { get; set; }

    public string PersonType { get; set; }

    public string OperationNumber { get; set; }

    public string SucCode { get; set; }

    public string GaveDate { get; set; }

    public string ExpDate { get; set; }

    public decimal ActualDebt { get; set; }

    public decimal DwellingDebt { get; set; }

    public decimal ExpiredDebt { get; set; }

    public decimal InExecutionDebt { get; set; }

    public string InExecutionDes { get; set; }

    public decimal ContingentDebt { get; set; }

    public decimal PunishedDebt { get; set; }

    public string PunishedDes { get; set; }

    public string WarrantyType { get; set; }

    public string Currency { get; set; }

    public string Category { get; set; }

    public string IdOrDestiny { get; set; }

    public string TypeOrDestiny { get; set; }

    public decimal OriginalAmount { get; set; }

    public decimal InterestToEarn { get; set; }

    public decimal SuspenseInterest { get; set; }

    public decimal WarrantyValue { get; set; }

    public string InterestRate { get; set; }

    public string PayWay { get; set; }

    public string GracePeriod { get; set; }

    public string PaymentsQty { get; set; }

    public string CreditorName { get; set; }

    public string Clasificacion { get; set; }

    public string IdcreditorName { get; set; }
}