// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class EquifaxConfiguracione
{
    public string FcUrl { get; set; }

    public string FcUsuario { get; set; }

    public string FcPassword { get; set; }

    public string FdUltimoCambio { get; set; }

    public string FcPassword1 { get; set; }

    public string FcPassword2 { get; set; }

    public string FcPassword3 { get; set; }

    public string FcPassword4 { get; set; }

    public string FcPassword5 { get; set; }
}