// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class EquifaxClientesEstadoPrecalificado
{
    public int FiEstadoPrecalificado { get; set; }

    public string FcEstadoPrecalificado { get; set; }

    public string FcToken { get; set; }
}