// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class EquifaxTelefono
{
    public int FiIdequifax { get; set; }

    public string FcIdentidad { get; set; }

    public string NumeroTelefono { get; set; }

    public string PeriodoInformacion { get; set; }

    public string TipoTelefono { get; set; }

    public string FechaInformacion { get; set; }

    public string NombreAcreedor { get; set; }

    public string CodigoAcreedor { get; set; }
}