// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class EquifaxMaximoDiasAtrasoBanca24M
{
    public int FiIdequifax { get; set; }

    public string FcIdentidad { get; set; }

    public string PeriodoActual { get; set; }

    public string PeriodoInformacion { get; set; }

    public int DiasAtrasoMaximo { get; set; }

    public string Acreedor { get; set; }

    public string CodigoFuente { get; set; }
}