// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class EquifaxClientePerfil
{
    public int FiIdequifax { get; set; }

    public string FcIdentidad { get; set; }

    public byte FiOrigenIngresos { get; set; }

    public byte FiTieneCasaPropia { get; set; }

    public short FiAntiguedadLaboral { get; set; }

    public byte FiMaquilaoCallCenter { get; set; }

    public byte FiEsGuardiadeSeguridad { get; set; }

    public byte FiPermisodeOperacionVigente { get; set; }

    public byte FiAntiguedadNegocio { get; set; }

    public int FiIdproductoPrecalificado { get; set; }

    public int FiIdperfil { get; set; }
}