// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class EquifaxTardeudaExtrafinanciamiento
{
    public int FiIdequifax { get; set; }

    public string FcIdentidad { get; set; }

    public string PeriodoInformacionExt { get; set; }

    public string FechaOtorgamientoExt { get; set; }

    public string FechaCancelacionExt { get; set; }

    public string MondedaMontoExt { get; set; }

    public string MontoExt { get; set; }

    public string MondedaSaldoExt { get; set; }

    public string SaldoExt { get; set; }

    public string MonedaPagoMinimoExt { get; set; }

    public string PagoMinimoExt { get; set; }

    public string PlazoExt { get; set; }

    public string FactorCambioExt { get; set; }

    public string FechaMoraExt { get; set; }

    public string MonedaMoraExt { get; set; }

    public string SaldoMoraCapitalExt { get; set; }

    public string SaldoMoraInteresExt { get; set; }

    public string FechaVencimientoExt { get; set; }

    public string CodigoFuenteExt { get; set; }

    public string Referencia { get; set; }

    public string NumeroExtrafinanciamiento { get; set; }
}