// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class EquifaxCatalogoOperacion
{
    public short FiIdoperacion { get; set; }

    public string FcOperacion { get; set; }
}