// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class EquifaxInfoConsulta
{
    public int FiIdequifax { get; set; }

    public string FcIdentidad { get; set; }

    public string ViewId { get; set; }

    public string CandidateCorrelative { get; set; }

    public string ViewLength { get; set; }

    public string ViewReturnCode { get; set; }

    public string InfoPeriod { get; set; }

    public string ActualPeriod { get; set; }

    public string WhoMadeQuery { get; set; }

    public string QueryDate { get; set; }

    public string OfficeCode { get; set; }

    public string EntityCode { get; set; }
}