// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class EquifaxClienteTipoPersona
{
    public int? FiIdequifax { get; set; }

    public int FiIdsolicitud { get; set; }

    public int? FiIdtipoPersona { get; set; }

    public string FcNombre { get; set; }

    public string FcRtn { get; set; }

    public DateTime? FdFechaCreacion { get; set; }

    public int? FiIdusuario { get; set; }
}