// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class EquifaxTardeudum
{
    public int FiIdequifax { get; set; }

    public string FcIdentidad { get; set; }

    public string CoverageCode { get; set; }

    public string Coverage { get; set; }

    public string ActualPeriod { get; set; }

    public string CurrencyTypeGivedLimit { get; set; }

    public string GivedLimit { get; set; }

    public string AditionalCardsQuantity { get; set; }

    public string PeorNivelTardeuda { get; set; }

    public string Referencia { get; set; }

    public string ViewId { get; set; }

    public string OpenningDate { get; set; }

    public string CancelationDate { get; set; }

    public string InfoSource { get; set; }

    public string InfoDate { get; set; }

    public string DebtCurrencyType { get; set; }

    public string PaymentCurrencyType { get; set; }

    public string AccountStatus { get; set; }

    public string StatusDate { get; set; }

    public string DwellLevel { get; set; }

    public string DwellCurency { get; set; }

    public string DwellDate { get; set; }

    public string ViewLength { get; set; }

    public string InfoPeriod { get; set; }

    public string Debt { get; set; }

    public string PaymentValue { get; set; }

    public string DwellingDebt { get; set; }

    public string ViewReturnCode { get; set; }

    public string ChangeFactor { get; set; }

    public string OverdraftDollar { get; set; }

    public string OverdraftLempira { get; set; }

    public string DwellCountDollar { get; set; }

    public string DwellCountLempira { get; set; }

    public string CandidateCorrelative { get; set; }

    public string IdInfoSource { get; set; }

    public string FechaOtorgamientoExtrafinanciamiento1 { get; set; }

    public string MontoExtrafinanciamiento1 { get; set; }

    public string SaldoExtrafinanciamiento1 { get; set; }

    public string PlazoExtrafinanciamiento1 { get; set; }

    public string FechaOtorgamientoExtrafinanciamiento2 { get; set; }

    public string MontoExtrafinanciamiento2 { get; set; }

    public string SaldoExtrafinanciamiento2 { get; set; }

    public string PlazoExtrafinanciamiento2 { get; set; }

    public string FechaOtorgamientoExtrafinanciamiento3 { get; set; }

    public string MontoExtrafinanciamiento3 { get; set; }

    public string SaldoExtrafinanciamiento3 { get; set; }

    public string PlazoExtrafinanciamiento3 { get; set; }

    public string FechaOtorgamientoExtrafinanciamiento4 { get; set; }

    public string MontoExtrafinanciamiento4 { get; set; }

    public string SaldoExtrafinanciamiento4 { get; set; }

    public string PlazoExtrafinanciamiento4 { get; set; }
}