// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class EquifaxAddress
{
    public int FiIdequifax { get; set; }

    public string FcIdentidad { get; set; }

    public string ViewLength { get; set; }

    public string ViewReturnCode { get; set; }

    public string ViewId { get; set; }

    public string DebtorAddress { get; set; }

    public string InformationPeriod { get; set; }

    public string CandidateCorrelative { get; set; }
}