// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class EquifaxBitacoraWebService
{
    public int FiIdequifax { get; set; }

    public string FcIdentidad { get; set; }

    public DateTime FdBitacora { get; set; }

    public string FcCentrodeCosto { get; set; }

    public short FiIdapp { get; set; }

    public int FiIdusuario { get; set; }

    public string FcCodigoRespuestaEquifax { get; set; }

    public string FcMensajeEquifax { get; set; }
}