// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class EquifaxCatalogoEstado
{
    public int FiIdestadoPrecalificado { get; set; }

    public string FcDescripcion { get; set; }
}