// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class EquifaxCatalogoPerfile
{
    public string FcPerfilAsignado { get; set; }

    public string FcDescripcionPerfil { get; set; }

    public string FcAccionPerfil { get; set; }

    public byte FiOrigenIngresos { get; set; }
}