// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class EquifaxReferenciasImpugnada
{
    public int FiIdequifax { get; set; }

    public string FcIdentidad { get; set; }

    public string TipoInformacion { get; set; }

    public string NombreAcreedor { get; set; }

    public string NumeroReferencia { get; set; }

    public string FechaReclamo { get; set; }
}