// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class EquifaxPrimeraReferenciaTardeudum
{
    public int FiIdequifax { get; set; }

    public string FcIdentidad { get; set; }

    public string StatusCode { get; set; }

    public string CoverageCode { get; set; }

    public string Coverage { get; set; }

    public string ActualPeriod { get; set; }

    public string CurrencyTypeGivedLimit { get; set; }

    public string GivedLimit { get; set; }

    public string Referencia { get; set; }

    public string ViewId { get; set; }

    public string OpenningDate { get; set; }

    public string CancelationDate { get; set; }

    public string InfoSource { get; set; }

    public string InfoDate { get; set; }

    public string DebtCurrencyType { get; set; }

    public string PaymentCurrencyType { get; set; }

    public string AccountStatus { get; set; }

    public string DwellLevel { get; set; }

    public string DwellDate { get; set; }

    public string DwellCurency { get; set; }

    public string ViewLength { get; set; }

    public string InfoPeriod { get; set; }

    public string Debt { get; set; }

    public string PaymentValue { get; set; }

    public string DwellingDebt { get; set; }

    public string ViewReturnCode { get; set; }

    public string ChangeFactor { get; set; }

    public string CandidateCorrelative { get; set; }

    public string IdInfoSource { get; set; }

    public string MonedaMontoOtorgadoExtraf1 { get; set; }

    public string MontoOtorgadoExtrafinanciamiento1 { get; set; }

    public string MonedaSaldoExtraf1 { get; set; }

    public string SaldoExtrafinanciamiento1 { get; set; }

    public string MonedaMontoOtorgadoExtraf2 { get; set; }

    public string MontoOtorgadoExtrafinanciamiento2 { get; set; }

    public string MonedaSaldoExtraf2 { get; set; }

    public string SaldoExtrafinanciamiento2 { get; set; }

    public string MonedaMontoOtorgadoExtraf3 { get; set; }

    public string MontoOtorgadoExtrafinanciamiento3 { get; set; }

    public string MonedaSaldoExtraf3 { get; set; }

    public string SaldoExtrafinanciamiento3 { get; set; }

    public string MonedaMontoOtorgadoExtraf4 { get; set; }

    public string MontoOtorgadoExtrafinanciamiento4 { get; set; }

    public string MonedaSaldoExtraf4 { get; set; }

    public string SaldoExtrafinanciamiento4 { get; set; }
}