// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class EquifaxAtrasosMoraHisComTar
{
    public int FiIdequifax { get; set; }

    public string FcIdentidad { get; set; }

    public string PeriodoActual { get; set; }

    public string PeriodoInformacion { get; set; }

    public string TipoAcreedores { get; set; }

    public int DiasAtrasoMaximo { get; set; }

    public int DiasAtrasoMinimo { get; set; }
}