// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class EquifaxCatalogoOcupacione
{
    public int FiIdocupacion { get; set; }

    public string FcOcupacion { get; set; }

    public int FiIdperfilPrecalificado { get; set; }
}