// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class EquifaxFiadoresDeudaComercial
{
    public int FiIdequifax { get; set; }

    public string FcIdentidad { get; set; }

    public string ActualPeriod { get; set; }

    public string InfoPeriod { get; set; }

    public string Guarantor { get; set; }

    public string CreditType { get; set; }

    public string OpenningDate { get; set; }

    public string LastDate { get; set; }

    public string AccountStatus { get; set; }

    public short AmountCurrencyType { get; set; }

    public decimal GivedAmount { get; set; }

    public short DebtCurrencyType { get; set; }

    public decimal Debt { get; set; }

    public short DwellCurrencyType { get; set; }

    public decimal DwellingDebt { get; set; }

    public string NumeroTip { get; set; }

    public string NumeroNit { get; set; }

    public string NumeroIfi { get; set; }

    public string NumeroPas { get; set; }

    public string NumeroCre { get; set; }

    public string InfoSource { get; set; }

    public string IdInfoSource { get; set; }

    public string ChangeFactor { get; set; }

    public short CandidateCorrelative { get; set; }
}