// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class FirmaTokenOrion
{
    public int FiIdtoken { get; set; }

    public int? FiIdfirma { get; set; }

    public int? FiIdestado { get; set; }

    public DateTime? FdFechaCreacion { get; set; }

    public string FcToken { get; set; }
}