// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class FirmasOrion
{
    public int FiIdfirma { get; set; }

    public int? FiIdsolicitud { get; set; }

    public int? FiIdestado { get; set; }

    public DateTime? FdFechaFirma { get; set; }

    public string FcFirma { get; set; }

    public int? FiIdtipoDocumento { get; set; }
}