// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class GeoMunicipio
{
    public short FiCodPais { get; set; }

    public short FiCodDepartamento { get; set; }

    public short FiCodMunicipio { get; set; }

    public string FcMunicipio { get; set; }
}