// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class GeoPai
{
    public int FiCodPais { get; set; }

    public string FcPais { get; set; }

    public string FcNombreMoneda { get; set; }

    public string FcAbreviacionMoneda { get; set; }

    public string FcSimboloMoneda { get; set; }

    public string FcDominoInternet { get; set; }
}