// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class Ihss
{
    public string FcIdentidad { get; set; }

    public string FcNombreEmpresa { get; set; }

    public string FcRazonEmpresa { get; set; }

    public string FcDireccionEmpresa { get; set; }

    public string FcTelefonoEmpresa { get; set; }

    public string FcNombreEmpleado { get; set; }

    public string FcDireccion2 { get; set; }

    public string FcCiudad { get; set; }

    public string FcTelefono1 { get; set; }

    public string FcTelefono2 { get; set; }

    public string FcTelefono3 { get; set; }
}