// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class InventarioMovimientoMaestro
{
    public int FiIdinventarioMovimientoMaestro { get; set; }

    public int FiIdubicacion { get; set; }

    public int FiIdusuarioDestino { get; set; }

    public int FiIdusuarioCreado { get; set; }

    public DateTime FdFechaCreacion { get; set; }

    public int FiIdusuarioUltimaModificacion { get; set; }

    public DateTime FdFechaUltimaModificacion { get; set; }

    public int FiFirma { get; set; }

    public string FcDocumentoFirma { get; set; }

    public int FiEstadoInventairoMovimientoMaestro { get; set; }

    public string FcToken { get; set; }

    public int FiIdtipoMovimiento { get; set; }

    public int? FiIdubicacionDestino { get; set; }

    public virtual ICollection<ContratistaSolicitudInstalacion> ContratistaSolicitudInstalacions { get; set; } = new List<ContratistaSolicitudInstalacion>();
}