// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class ListaNegraIdentidad
{
    public int FiIdsesion { get; set; }

    public int FiIdusuario { get; set; }

    public string FcIdentidad { get; set; }

    public string FcRazon { get; set; }

    public DateTime FdRegistro { get; set; }
}