// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class ListaNegraTelefono
{
    public string FcTelefono { get; set; }

    public DateTime FdRegistro { get; set; }

    public string FcCentrodeCosto { get; set; }

    public short FiIdapp { get; set; }

    public int FiIdusuario { get; set; }

    public string FcObservaciones { get; set; }
}