// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class OrionEstadodeCuentaUsuario
{
    public int FiIdunico { get; set; }

    public DateTime FdFechaRegistro { get; set; }

    public DateTime FdFechaMovimiento { get; set; }

    public int FiIdusuarioMovimiento { get; set; }

    public int FiIdusuarioAsignado { get; set; }

    public int FiIdequifax { get; set; }

    public int FiIdsolicitud { get; set; }

    public byte FiTipoMovimiento { get; set; }

    public decimal? FnValorMovimiento { get; set; }

    public string FcReferencia { get; set; }

    public string FcToken { get; set; }
}