// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class OrionEstadodeCuentaUsuarioCatalogoTipoMovimiento
{
    public byte FiTipoMovimiento { get; set; }

    public string FcTipoMovimiento { get; set; }

    public decimal? FnTipoAfectacion { get; set; }

    public string FcToken { get; set; }
}