// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class OrionSolicitudDetalleClienteServicioContratado
{
    public int FiIddetalleClienteServicio { get; set; }

    public int FiIdorionSolicitud { get; set; }

    public int FiIdolt { get; set; }

    public string FcMac { get; set; }

    public string FcIp { get; set; }

    public string FcPom { get; set; }

    public string FcNombreWifi { get; set; }

    public int FiUsuarioCreacion { get; set; }

    public DateTime FdFechaCreacion { get; set; }

    public int? FiUsuarioModificacion { get; set; }

    public DateTime? FdFechaModificacion { get; set; }
}