// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class OrionSolicitudDocumento
{
    public int FiIdorionDocumento { get; set; }

    public int FiIdorionSolicitud { get; set; }

    public string FcNombreArchivo { get; set; }

    public string FcExtension { get; set; }

    public string FcRutaArchivo { get; set; }

    public string FcUrl { get; set; }

    public int? FiIddocumento { get; set; }

    public string FcComentario { get; set; }

    public byte? FiArchivoActivo { get; set; }

    public int? FiIdusuarioCreador { get; set; }

    public DateTime? FdFechaCreado { get; set; }

    public string FcHashTag { get; set; }

    public int? FiEstadoFirmaDocumento { get; set; }

    public int? FiIdsolicitudFirma { get; set; }
}