// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class OrionSolicitudEquifaxCliente
{
    public int FiIdorionSolicitudEquifaxCliente { get; set; }

    public int? FiIdequifaxCliente { get; set; }

    public int? FiIdsolicitud { get; set; }

    public string FcCodigoCliente { get; set; }

    public int? FiNumeroConsecutivoCliente { get; set; }
}