// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class OrionCatalogoGestion
{
    public byte FiIdgestion { get; set; }

    public string FcGestion { get; set; }

    public byte FiTipoGestion { get; set; }

    public byte FiSeguimiento { get; set; }

    public byte FiFavorable { get; set; }

    public byte FiActualizaDatos { get; set; }

    public byte FiRequiereDocumentos { get; set; }

    public byte FiOpcionManual { get; set; }

    public byte FiTipoPuesto { get; set; }

    public byte FiContactado { get; set; }
}