// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class OrionSolicitudMaestro
{
    public int FiIdsolicitud { get; set; }

    public int FiIdcliente { get; set; }

    public int? FiPlazoSeleccionado { get; set; }

    public int FiEstadoSolicitud { get; set; }

    public decimal? FnValorGarantia { get; set; }

    public decimal? FnMontoFinalFinanciar { get; set; }

    public string FcComentarioResolucion { get; set; }

    public DateTime? FdFechaCreacionSolicitud { get; set; }

    public DateTime? FdFinFirma { get; set; }

    public decimal? FnTasaMensual { get; set; }

    public decimal? FnCuotaMensual { get; set; }

    public decimal? FnTasaAnual { get; set; }

    public DateTime? FdFechaIniciodeCredito { get; set; }

    public int? FiIdmoneda { get; set; }

    public int? FiIdfondo { get; set; }

    public int? FiIdestadoPago { get; set; }

    public DateTime? FdFechaFinalizaciondeCredito { get; set; }

    public decimal? FnTotalValorContrato { get; set; }

    public int? FiIdpagoInicial { get; set; }

    public string FcComentarioPagoInicial { get; set; }

    public DateTime? FdFechaPagoInicial { get; set; }

    public decimal? FnValorReembolso { get; set; }

    public string FcIdprestamo { get; set; }

    public int? FiIdusuario { get; set; }

    public int? FiIdtipoSolicitud { get; set; }

    public int? FiIdorigen { get; set; }

    public string FcOrigen { get; set; }

    public string FcCodigoVendedor { get; set; }

    public int? FiIdtipoCliente { get; set; }

    public string FcNombreEmpresaJuridica { get; set; }

    public string FcRtnEmpresaJuridico { get; set; }

    public int? FiIdidentidadSubida { get; set; }

    public int? FiIdselfieSubida { get; set; }

    public int? FiDiaPago { get; set; }

    public virtual ICollection<SolicitudesAdicionProductoMaestro> SolicitudesAdicionProductoMaestros { get; set; } = new List<SolicitudesAdicionProductoMaestro>();
}