// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class OrionSolicitudHistorialMantenimiento
{
    public int FiIdsolicitudHistorialMantenimiento { get; set; }

    public int? FiIdsolicitud { get; set; }

    public string FcOpcionSeleccionada { get; set; }

    public int? FiIdusuario { get; set; }

    public DateTime? FdFechaMantenimiento { get; set; }

    public string FcObservaciones { get; set; }

    public bool? FiEstadoMantenimiento { get; set; }
}