// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class PagosPaginaWebDeposito
{
    public int FiIdunico { get; set; }

    public int FiIdusuarioOrigen { get; set; }

    public short FiIdapp { get; set; }

    public string FcIdcliente { get; set; }

    public string FcNombreCliente { get; set; }

    public string FcTelefonoCliente { get; set; }

    public decimal FnValordelDeposito { get; set; }

    public DateTime FdFechaRegistro { get; set; }

    public string FcComentarioCliente { get; set; }

    public string FcArchivo { get; set; }

    public string FcUbicacionLocal { get; set; }

    public string FcUrlarchivo { get; set; }

    public string FcIpservidorUbicacion { get; set; }

    public int FiIdusuarioAplicaPago { get; set; }

    public DateTime? FdFechaAplicaPago { get; set; }

    public int FiIdtransaccion { get; set; }

    public string FcComentarioUsuario { get; set; }

    public byte FiEstadodelDeposito { get; set; }

    public string FcIpcliente { get; set; }

    public string FcIpusuario { get; set; }

    public string FcToken { get; set; }
}