// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class ParametrosConversionDeMoneda
{
    public decimal FiAno { get; set; }

    public byte FiMes { get; set; }

    public short FiCodPaisOrigen { get; set; }

    public short FiCodPaisDestino { get; set; }

    public decimal? FnTasadeCambio { get; set; }
}