// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class PrivilegiosPorRol
{
    public int PkIdPrivilegiosPorRol { get; set; }

    public int FkIdRol { get; set; }

    public string FkIdPermiso { get; set; }

    public virtual AspNetRole FkIdPermisoNavigation { get; set; }

    public virtual Role FkIdRolNavigation { get; set; }
}