// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class ProductoPreciosDetalle
{
    public int FiIdProductoPreciosDetalle { get; set; }

    public int? FiIdproducto { get; set; }

    public decimal? FnValorProductoMn { get; set; }

    public decimal? FnValorProductoMe { get; set; }

    public decimal? FnPorcentajeImpuesto1 { get; set; }

    public decimal? FnPorcentajeImpuesto2 { get; set; }

    public decimal? FnValorCuotaMensual { get; set; }

    public decimal? FnValorCuotaCapital { get; set; }

    public decimal? FnValorCuotaInteres { get; set; }

    public decimal? FnTasaAnualPlana { get; set; }

    public DateTime? FdFechaCreacion { get; set; }

    public int? FiIdusuarioCreacion { get; set; }

    public DateTime? FdFechaUltimaModificacion { get; set; }

    public int? FiIdusuarioUltimaModificacion { get; set; }

    public string FcToken { get; set; }

    public bool? FbEstadoPrecioActual { get; set; }

    public bool? FbEstadoPrecio { get; set; }

    public decimal? FnValorCuotaMensual12Cliente { get; set; }

    public decimal? FnValorCuotaMensual24Cliente { get; set; }

    public decimal? FnValorCuotaMensual12Nuevo { get; set; }

    public decimal? FnValorCuotaMensual24Nuevo { get; set; }

    public virtual ICollection<ProductosMovimientosDetalle> ProductosMovimientosDetalles { get; set; } = new List<ProductosMovimientosDetalle>();
}