// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class ProductosMovimientosDetalle
{
    public int FiIdmovimiento { get; set; }

    public int FiIdproducto { get; set; }

    public int FiIdubicacion { get; set; }

    public byte FiTipoMovimiento { get; set; }

    public string FcCodigoSerie1 { get; set; }

    public string FcCodigoSerie2 { get; set; }

    public string FcReferenciaMovimiento { get; set; }

    public DateTime FdFechaMovimiento { get; set; }

    public int FiIdusuarioMovimiento { get; set; }

    public string FcToken { get; set; }

    public int? FiIdmovimientoMaestro { get; set; }

    public decimal FnCantidad { get; set; }

    public int? FiIdProductoPreciosDetalle { get; set; }

    public virtual ProductoPreciosDetalle FiIdProductoPreciosDetalleNavigation { get; set; }
}