// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class ProductosInventario
{
    public int FiIdproducto { get; set; }

    public int FiIdubicacion { get; set; }

    public decimal FnCantidad { get; set; }

    public string FcNumerodeSerie1 { get; set; }

    public string FcNumerodeSerie2 { get; set; }

    public byte FiIdestadoInventario { get; set; }

    public int? FiIdcliente { get; set; }

    public int? FiIdsolicitud { get; set; }

    public DateTime FdFechaCreacion { get; set; }

    public int FiIdusuarioCreacion { get; set; }

    public DateTime FdFechaUltimaModificacion { get; set; }

    public int FiIdusuarioUltimaModificacion { get; set; }

    public string FcToken { get; set; }
}