// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class ProductosMaestro
{
    public int FiIdproducto { get; set; }

    public string FcCodigodeBarras { get; set; }

    public string FcProducto { get; set; }

    public string FcImagenProducto { get; set; }

    public byte FiIdmarca { get; set; }

    public byte FiIdmodelo { get; set; }

    public byte FiIdtipoProducto { get; set; }

    public decimal FnValorProductoMn { get; set; }

    public decimal FnValorProductoMe { get; set; }

    public decimal FnPorcentajeImpuesto1 { get; set; }

    public decimal FnPorcentajeImpuesto2 { get; set; }

    public byte FiEstadoProducto { get; set; }

    public byte FiProductoInventariable { get; set; }

    public DateTime FdFechaCreacion { get; set; }

    public int FiIdusuarioCreacion { get; set; }

    public DateTime FdFechaUltimaModificacion { get; set; }

    public int FiIdusuarioUltimaModificacion { get; set; }

    public string FcToken { get; set; }

    public decimal FnValorCuotaMensual { get; set; }

    public decimal? FnValorCuotaCapital { get; set; }

    public decimal? FnValorCuotaInteres { get; set; }

    public decimal? FnTasaAnualPlana { get; set; }

    public int? FiProductoEnPaquete { get; set; }

    public DateTime? FdFechaUltimaActualizacion { get; set; }

    public int? FiEstadoPrecioActual { get; set; }

    public int? FiIdTipoDeProductoContable { get; set; }

    public decimal? FnValorCuotaMensual12Cliente { get; set; }

    public decimal? FnValorCuotaMensual24Cliente { get; set; }

    public decimal? FnValorCuotaMensual12Nuevo { get; set; }

    public decimal? FnValorCuotaMensual24Nuevo { get; set; }

    public bool? FbProductoSeleccionablePorCliente { get; set; }

    public virtual CatalogoTipoDeProductoContable FiIdTipoDeProductoContableNavigation { get; set; }

    public virtual ICollection<SolicitudesAdicionProductoDetalle> SolicitudesAdicionProductoDetalles { get; set; } = new List<SolicitudesAdicionProductoDetalle>();
}