// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class Role
{
    public int PkIdRol { get; set; }

    public string Nombre { get; set; }

    public bool Activo { get; set; }

    public string Observacion { get; set; }

    public virtual ICollection<PrivilegiosPorRol> PrivilegiosPorRols { get; set; } = new List<PrivilegiosPorRol>();

    public virtual ICollection<RolesPorUsuario> RolesPorUsuarios { get; set; } = new List<RolesPorUsuario>();
}