// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class RolesPorUsuario
{
    public int PkIdRolesPorUsuario { get; set; }

    public int FkIdUsuario { get; set; }

    public int FkIdRol { get; set; }

    public virtual Role FkIdRolNavigation { get; set; }

    public virtual UsuariosMaestro FkIdUsuarioNavigation { get; set; }
}