// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class SolicitudInstalacionDocumento
{
    public int FiIdsolicitudInstalacion { get; set; }

    public int? FiIdcontratistaSolicitud { get; set; }

    public int? FiIdcatalogoFotoInstalacion { get; set; }

    public string FcUrlDocumento { get; set; }

    public string FcNombreDocumento { get; set; }

    public string FcExtension { get; set; }
}