// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class SolicitudesAdicionProductoDetalle
{
    public int FiIdadicionProdutoDetalle { get; set; }

    public int? FiIdadicionProduto { get; set; }

    public int? FiIdproducto { get; set; }

    public int? FiCantidad { get; set; }

    public virtual SolicitudesAdicionProductoMaestro FiIdadicionProdutoNavigation { get; set; }

    public virtual ProductosMaestro FiIdproductoNavigation { get; set; }
}