// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class SolicitudInstalacionBitacora
{
    public int FiIdbitacoraSolicitudInstalacion { get; set; }

    public int? FiIdsolicitudInstalacion { get; set; }

    public string FcComentario { get; set; }

    public int? FiIdUsuarioCreacion { get; set; }

    public DateTime? FdFechaCreacion { get; set; }
}