// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Novanet.Entities.Entities;

public partial class TecnicosPorContratistum
{
    public int FiIdtecnicosPorContratista { get; set; }

    public int FiIdusuarioContratista { get; set; }

    public int FiIdusuarioTecnico { get; set; }

    public DateTime FdFechaCreacion { get; set; }

    public int FiIdusuarioCreacion { get; set; }

    public DateTime FdFechaUltimaModificacion { get; set; }

    public int FiIdusuarioUltimaModificacion { get; set; }

    public string FcToken { get; set; }

    public int? FiEstadoTecnicoPorContratista { get; set; }
}